mod ejercicios_1_al_5;


fn main() {
    // ESTA ES LA SOLUCION A MODO PRACTICA DE LA GUIA DE EJERCICIOS DE projecteuler.net

    // If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is $23$.</p>
    // Find the sum of all the multiples of 3 or 5 below 1000.
    let _numero_ejemp1 = 9;
    ejercicios_1_al_5::suma_multiplos_5_and_9(_numero_ejemp1);


    // <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
// $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

let _numero_ejemp2 = 4000000;
let imprimir_secuencia: Vec<u64>=ejercicios_1_al_5::suma_pares_fibonacci_hasta_4milliones(_numero_ejemp2);
println!("La secuencia fibonacci de numeros pares es {:?}", imprimir_secuencia )





}