mod ejercicios_1_al_5;


fn main() {
    // ESTA ES LA SOLUCION A MODO PRACTICA DE LA GUIA DE EJERCICIOS DE projecteuler.net

    // If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is $23$.</p>
    // Find the sum of all the multiples of 3 or 5 below 1000.
    let _numero_ejemp1 = 9;
    ejercicios_1_al_5::suma_multiplos_5_and_9(_numero_ejemp1);


    // <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
// $$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>

let _numero_ejemp2 = 4000000;
let imprimir_secuencia: Vec<u64>=ejercicios_1_al_5::suma_pares_fibonacci_hasta_4milliones(_numero_ejemp2);
println!("La secuencia fibonacci de numeros pares es {:?}", imprimir_secuencia );



// Voy a probar en el main problem 3 
println!("Problem 3");

let numbber_problem3 = 600851475143;

let vectores_primosej3: Vec<u64>= ejercicios_1_al_5::calcular_numero_primo_mayor(numbber_problem3);

println!("Los numeros primos son {:?}", vectores_primosej3);
// Los numeros primos son [71, 839, 1471, 6857]

println!("El mayor de los primos es: (Lo sabemos usando el metodo .last) {:?}", vectores_primosej3.last().unwrap());



}